### ISSUE TITLE
Question regarding function inputs.

### ISSUE THREAD

**Issue by Shuhaoalex** [alecjacobson/computer-graphics-raster-images#10]
When I was working with the function rgba_to_rgb and write_ppm, it seems that something went wrong with the function inputs. The input width is 0, the input height is 5079144 and the size of the input vector is 0. Can anyone help me with this?

**Comment by Shuhaoalex** [comment]
Yes, they are wrong for both functions, and I did not set them manually by myself and I did not modify the main function either. I found that the first function called in main was `read_rgba_from_png`, and it seems that this should be the function which will assign values to width and height. However, when I print out the value of width and height before and after the function was called, I found that the value of them did not change at all, which is the value I mentioned above. The image I used was the default images.

**Comment by psarahdactyl** [comment]
Is it wrong for all the functions? Do you get any other errors? What platform are you using to develop?

**Comment by Shuhaoalex** [comment]
I checked the value of these inputs in the main function by using `printf`, and the values I got was mentioned in the comment. As I have a 0 for width or height, the functions I wrote will basically do nothing at all, so I have not gotten any other errors.
The platform I am using is Windows10 and I am using Code::Blocks to build and run my assignment.

**Comment by psarahdactyl** [comment]
I don't know anything about Code::Blocks, but I'm guessing this software doesn't use VS solution files? How do you set up the project after running cmake?

**Comment by Shuhaoalex** [comment]
I just got the problem solved. Code::Blocks can automatically build and run the project, while the default running environment is the directory of `main.cpp`. And this leads to a problem that the default image directory in `main.cpp` is not correct. I need to manually run the `exe` file built by Code::Blocks in the `build` directory in order to get it running correctly.
