### ISSUE TITLE
desaturate to 25% or by 25%?

### ISSUE THREAD

**Issue by WilsonWangTHU** [alecjacobson/computer-graphics-raster-images#12]
Hi guys,

The reference de-saturated image seems to be desaturated **to** 25% instead of **by** 25%.

Is it something we should worry about, or was the reference image simply just made with some other random factor (which is not 25%)?

Thx in advance

**Comment by psarahdactyl** [comment]
yes, it is desaturated to 25%. You are right. I will look into this because the README does ask to desaturate the image _by_ a given factor.

**Comment by chenbowen** [comment]
So should we follow README or the reference image?

**Comment by johnkanji** [comment]
The reference image has been updated to agree with the README. You should desaturate _by_ a given factor, and the reference image has been desaturated _by_ 25%.

**Comment by Marina-t** [comment]
In the header file desaturate.h, the factor is defined as 
the fractional amount of saturation to keep [0,1]
but if I understand you correctly, we should treat the factor as the fractional amount of saturation to remove?
could you please verify if I understand correctly?

thanks

**Comment by psarahdactyl** [comment]
Since the instructions are conflicting, I'll give credit either way, but what you are describing is right. It should be the fractional amount to remove. I will change the header file for future classes.

**Comment by WilsonWangTHU** [comment]
thx @psarahdactyl    
i would consider this issue closed ;P
