### ISSUE TITLE
Bayer Mosaic Dimensions

### ISSUE THREAD

**Issue by krsh732** [alecjacobson/computer-graphics-raster-images#13]
Are we allowed to assume that Bayer mosaic images are at least 2x2 in dimensions?
If not, what do we do for a Bayer mosaic image that looks like the following?

![image](https://user-images.githubusercontent.com/25255817/45721044-8b272900-bb74-11e8-888e-5c7f6f36190e.png)

In the above image we have no neighboring red pixels to use for averaging, so how do we fill the red component for each pixel?

**Comment by psarahdactyl** [comment]
Yes, you can assume that they are big enough to perform the demosaic function.
