### ISSUE TITLE
is float 60.5 be rounded to 60 ok?

### ISSUE THREAD

**Issue by RioAraki** [alecjacobson/computer-graphics-raster-images#16]
I observed that for example float 60.5 is rounded to 60 when cast to unsigned char from float. Is this okay or we are expected to round it up to 61

**Comment by chenbowen** [comment]
Will we lose mark for using round()?

**Comment by johnkanji** [comment]
`round()` is part of `<cmath>` which is on the whitelist and thus fair game.
