### ISSUE TITLE
rgba_to_rgb: do we just discard alpha values?

### ISSUE THREAD

**Issue by krsh732** [alecjacobson/computer-graphics-raster-images#18]
Sorry for this rather silly question. I just want to make sure I am not oversimplifying/misunderstanding the problem.

For `rgba_to_rgb` do we simply discard the alpha values and write the rgb values? For example, if the `rgba` vector was (255, 0, 255, 31) the resulting `rgb` vector will be (255, 0, 255)?

**Comment by psarahdactyl** [comment]
Yep, that's all you need to do!
