### ISSUE TITLE
Bayer Pattern

### ISSUE THREAD

**Issue by Kennnyoung** [alecjacobson/computer-graphics-raster-images#23]
What pattern do we need to produce? BGGR or GBRG?? Does it even matter? Below is the comments in header file and it contradicts itself.

// Given a mosaiced image (interleaved **BGGR** colors in a single channel), created
// a 3-channel rgb image.
//
// Inputs:
//   bayer  width*height array containing interleaved color intensities in
//     the **GBRG** bayer pattern.

**Comment by Kennnyoung** [comment]
also in assignment instruction, the paragraph says we should do GBRG, then all the pictures all showing BGGR

**Comment by psarahdactyl** [comment]
It doesn't matter. They all have twice as much green than blue or red. As long as you are consistent between the `simulate_bayer_mosaic.cpp` and `demosaic.cpp` functions then it won't matter.
