### ISSUE TITLE
hue shift image has specs

### ISSUE THREAD

**Issue by sahilgadhok** [alecjacobson/computer-graphics-raster-images#24]
<img width="1280" alt="screen shot 2018-09-21 at 3 42 10 pm" src="https://user-images.githubusercontent.com/25038616/45905679-2c092480-bdbf-11e8-9dde-11a10fa337d0.png">
not sure why i get some specs around the image. is this how its supposed to be or am i missing something? my conversions from rgb to hsv and back are ok.

**Comment by psarahdactyl** [comment]
This is fine. The images on the web page are png's, which are compressed. This may have something to do with why it doesn't have specs.
