### ISSUE TITLE
make can't locate Eigen library?

### ISSUE THREAD

**Issue by Desmeister** [alecjacobson/computer-graphics-raster-images#27]
I'm on the Linux ECF machines and was having issues running the make command. I cloned a fresh copy of the repo and cmake from the build folder runs fine, but when I run make a host of errors all related to being unable to locate the eigen library are printed:

In file included from /u/c/sissonde/computer-graphics-ray-casting/include/Plane.h:4,
                 from /u/c/sissonde/computer-graphics-ray-casting/src/Plane.cpp:1:
/u/c/sissonde/computer-graphics-ray-casting/include/Object.h:4:22: error: Eigen/Core: No such file or directory
In file included from /u/c/sissonde/computer-graphics-ray-casting/include/Plane.h:4,
                 from /u/c/sissonde/computer-graphics-ray-casting/src/Plane.cpp:1:
/u/c/sissonde/computer-graphics-ray-casting/include/Object.h:24: error: ‘Eigen’ has not been declared
/u/c/sissonde/computer-graphics-ray-casting/include/Object.h:24: error: expected ‘,’ or ‘...’ before ‘&’ token
In file included from /u/c/sissonde/computer-graphics-ray-casting/src/Plane.cpp:1:
/u/c/sissonde/computer-graphics-ray-casting/include/Plane.h:11: error: ‘Eigen’ has not been declared
/u/c/sissonde/computer-graphics-ray-casting/include/Plane.h:11: error: ISO C++ forbids declaration of ‘Vector3d’ with no type
/u/c/sissonde/computer-graphics-ray-casting/include/Plane.h:11: error: expected ‘;’ before ‘point’
/u/c/sissonde/computer-graphics-ray-casting/include/Plane.h:13: error: ‘Eigen’ has not been declared
/u/c/sissonde/computer-graphics-ray-casting/include/Plane.h:13: error: ISO C++ forbids declaration of ‘Vector3d’ with no type
/u/c/sissonde/computer-graphics-ray-casting/include/Plane.h:13: error: expected ‘;’ before ‘normal’
/u/c/sissonde/computer-graphics-ray-casting/include/Plane.h:24: error: ‘Eigen’ has not been declared
/u/c/sissonde/computer-graphics-ray-casting/include/Plane.h:24: error: expected ‘,’ or ‘...’ before ‘&’ token
In file included from /u/c/sissonde/computer-graphics-ray-casting/src/Plane.cpp:2:
/u/c/sissonde/computer-graphics-ray-casting/include/Ray.h:8: error: ‘Eigen’ has not been declared
/u/c/sissonde/computer-graphics-ray-casting/include/Ray.h:8: error: ISO C++ forbids declaration of ‘Vector3d’ with no type
/u/c/sissonde/computer-graphics-ray-casting/include/Ray.h:8: error: expected ‘;’ before ‘origin’
/u/c/sissonde/computer-graphics-ray-casting/include/Ray.h:12: error: ‘Eigen’ has not been declared
/u/c/sissonde/computer-graphics-ray-casting/include/Ray.h:12: error: ISO C++ forbids declaration of ‘Vector3d’ with no type
/u/c/sissonde/computer-graphics-ray-casting/include/Ray.h:12: error: expected ‘;’ before ‘direction’
/u/c/sissonde/computer-graphics-ray-casting/src/Plane.cpp:5: error: ‘Eigen’ has not been declared
/u/c/sissonde/computer-graphics-ray-casting/src/Plane.cpp:5: error: expected ‘,’ or ‘...’ before ‘&’ token
make[2]: *** [CMakeFiles/raycasting.dir/src/Plane.cpp.o] Error 1
make[1]: *** [CMakeFiles/raycasting.dir/all] Error 2
make: *** [all] Error 2

I found a page on the Eigen home folder about using it in projects with cmake but didn't find anything relevant. Did I initialize something wrong?

**Comment by alecjacobson** [comment]
are you sure you did recursive clone?

**Comment by alecjacobson** [comment]
I’m working with CDF about download times. (On my home internet it only
takes 39secs)

**Comment by alecjacobson** [comment]
I've refactored the repository in  87acbc5. It now takes 4secs on teach.cs.
