### ISSUE TITLE
write ppm not working

### ISSUE THREAD

**Issue by yeqingxi** [alecjacobson/computer-graphics-raster-images#28]
Working on write_ppm.cpp, I'm using the following header:
P6
255
*width* *height*
But my image only displays a quarter of the dog.
I saw the rgb.ppm.png in the images folder and its width and height are twice that of the rgb.png, does that mean the width and height of the .ppm should be 2*width and 2*height?

**Comment by gmin7** [comment]
When you export your .ppm files, do they appear as black squares or can you actually open them to see the images? I'm able to feed text into the file but when opened it's a black square...

**Comment by yeqingxi** [comment]
I'm able to see the image. I've figured out how to solve it now actually, by changing my header a bit.
P3
255
*width* *height*
And when I write to the file, I cast the unsigned char as an integer.
