### ISSUE TITLE
clarify semi-transparent rgba images

### ISSUE THREAD

**Issue by Topaz666** [alecjacobson/computer-graphics-raster-images#30]
Does semi-transparent rgba images mean we need to change transparency to 0.5 out of 1 in the a and b RGBA? like in a from 255 to 255/2 and b from 0 to 255/2?

**Comment by WyattLiu** [comment]
if you are referring to A over B operation, there are many example formula to follow. You basically need to do RGB in one way and alpha channel in a similar way.

https://en.wikipedia.org/wiki/Alpha_compositing

I suggest not to search code from other people, you wont miss premultiplied RGB concept if you do from wiki which tricked me for a while.
