### ISSUE TITLE
4% color change by 1 during hsv Rgb conversions

### ISSUE THREAD

**Issue by WyattLiu** [alecjacobson/computer-graphics-raster-images#34]
When I wrote hue shift, I tested by converting from rgb to hsv then convert back, however, I noticed about 4% pixels, each pixel changes by 1 i.e. 134->135, this is probably due to accuracy issue of double and math libs, should I be worry about this?

**Comment by alecjacobson** [comment]
Sounds like an (slight) error in your implementation. Shifting by zero should produce the same image.
