### ISSUE TITLE
noise in hue shifted image

### ISSUE THREAD

**Issue by Lipai-1994** [alecjacobson/computer-graphics-raster-images#35]
From the some conversion formulas from internet, I get the following hue shift image. However, I can see some green noise in the image. Is this a fine output?
![shifted](https://user-images.githubusercontent.com/36057591/51216185-76c02680-18f1-11e9-8c19-bed91c275568.jpg)

**Comment by bod11** [comment]
This is not normal and there is a specific reason why this is happening. Think about the circumstances where noise appears that we went over in class.
