### ISSUE TITLE
Not quite understanding the error message in visual studio

### ISSUE THREAD

**Issue by Jimmie777** [alecjacobson/computer-graphics-raster-images#39]
I'm not very familiar with visual studio and it is producing this error
`Error		CMake Error at C:\Users\Jimmy\Source\Repos\Assignment1\alecjacobson\computer-graphics-raster-images\CMakeLists.txt:2 (project):
  No CMAKE_C_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.	raster	C:\Users\Jimmy\Source\Repos\Assignment1\alecjacobson\computer-graphics-raster-images\CMakeLists.txt	2	
`
Is the way I'm compiling on visual studio wrong? This is my first time using visual studio.

**Comment by Puneet119** [comment]
I had the same issue, did you figure out a solution?

**Comment by Jimmie777** [comment]
You simply have to download the window SDK tool in the visual studio installer :) I would still suggest using a virtual box if you are using windows though.

**Comment by alecjacobson** [comment]
I remember last year a student had good success with the bash subsystem on
windows

>
