### ISSUE TITLE
Clarification on simulate_bayer_mosaic

### ISSUE THREAD

**Issue by DavidCollard** [alecjacobson/computer-graphics-raster-images#4]
The README states that we need to _"Simulate an image acquired from the Bayer mosaic by taking a 3-channel rgb image and creating a single channel grayscale image composed of interleaved red/green/blue channels. The output image should be twice as big (but only one channel)."_

My first inclination is that we should be mapping one of each pixel's particular RGB value to greyscale output (ie; (0, 0) pixel only reports the green value, (1, 0) reports blue etc). This however, doesn't conform to the specification that the image should be twice as large.

My second though was to map each pixel in the input image to 4 separate grayscale pixels in the new image as per the Bayer pattern. However, in the starter code, the bayer matrix is resized to (width*height) instead of (width*height*4). Based on bayer.ppm.png (under /images, it has a height and width twice that of the other pngs), this is what I think we're supposed to do, but this should probably be reflected with a change to the starter code. This is also 4 times as large, not twice.

If one of the profs could clarify on this, it would be appreciated.

**Comment by alecjacobson** [comment]
Your first inclination is correct and the README was wrong (the .h was correct). I've fixed the readme.
