### ISSUE TITLE
Grayscale: PPM or PGM?

### ISSUE THREAD

**Issue by bryantam** [alecjacobson/computer-graphics-raster-images#5]
For the grayscale output, should it be a RGB .ppm file (with magic number P6), but visually in grayscale? Or should it be a real grayscale PGM (with magic number P5)?

**Comment by psarahdactyl** [comment]
In the `write_ppm.cpp` file you'll see that the number of channels that your output should be is either 1 or 3.  This leads me to believe that your resulting PPM will be a real grayscale image with size height*width. @alecjacobson is this correct?

Also, according to the [PPM specification](https://en.wikipedia.org/wiki/Netpbm_format#File_format_description), the magic numbers you list here are binary versions of the file. ASCII is probably sufficient for this assignment.

**Comment by zhtdavis** [comment]
For PPM, I think you have to write 3 channel values for each pixel. The num_channels variable is to help you how to interrupt the input 1d vector.

**Comment by bryantam** [comment]
@zhtdavis That's why I asked whether I should write 3 channels with the same value (P3 or P6), or 1 channel with a different magic number to signify a grayscale image (P2 or P5).

@psarahdactyl I found using binary version easier to implement. Can I use binary? Or must I use ASCII?

**Comment by zhtdavis** [comment]
The file you need to generate is *.ppm. I think you need to write the same to the three channel.

**Comment by bryantam** [comment]
Can we get an official answer from Prof or TA? @psarahdactyl @alecjacobson

**Comment by psarahdactyl** [comment]
Either one is fine; they'll look the same. Also, yes binary is fine too.

**Comment by RioAraki** [comment]
Cool, cuz I am afraid the assignment is judged by compare our output with some standard output and if we implement grayscle by 3 channel meanwhile standard solution expect one we might lose point on this.  So as long as the output looks visually correct we are fine right?

**Comment by psarahdactyl** [comment]
Yes, you'll be fine if you implement it either way described.
