### ISSUE TITLE
Porter/Duff over operator calculating resulting alpha value

### ISSUE THREAD

**Issue by glebka100500** [alecjacobson/computer-graphics-raster-images#50]
I am following the explanation of Porter/Duff operators from this page http://ssp.impulsetrain.com/porterduff.html and it's not clear to me how to calculate the resulting alpha value, what are the operators [as] [ad] [ab]? On the web page it says that these values should be 0 or 1 depending on whether source or destination pixel is present and [ab] should be 0 if both region is empty (so its 1 in our case). However if I use this formula I am getting a weird image where the dog is clearly visible but all the images after that are missing some colors. I am I using the formula wrong? I appreciate any help.

**Comment by chen290** [comment]
just use the one on wiki. alpha_c = alpha_a + alpha_b * (1-alpha_a). Also, did you divide a channel value by 255?

**Comment by glebka100500** [comment]
yeah, I divided before using alpha in the formula and then multiplied again before writing alpha value into C. I tried using the one on Wikipedia and I get more or less the same result, if I am using the formula for pixel value from wikipedia I should use the non premultiplied on, right? I seem to be getting the same result with both methods

**Comment by glebka100500** [comment]
Solved. Needed to divide by 255.0 since apparently c++ will cast result to integer if at least one of the operands is int

**Comment by chen290** [comment]
hmm, i thought c++ only cast to int if both operands are int?

**Comment by glebka100500** [comment]
My bad, you're right. Thanks for the help
