### ISSUE TITLE
Clarification on demosaic function

### ISSUE THREAD

**Issue by QiiLin** [alecjacobson/computer-graphics-raster-images#52]
Hi guys, I have read through the issue and read some documents online about the demosaic, however, I keep getting a greenish color image ..... what I did here is the following:
For example, if the current index in Bayer is a blue, ie(meaning it is on an even row and an odd column ) so I should just take avg value from its horizontal, vertical neighbors((4 of them) as value for red color and the avg value of its diagonal neighbors as value for green color(4 of them)..... I think I did it correctly however the image is still somewhat gree... what may be the cause of this? Can anyone give me some hint?
![image](https://user-images.githubusercontent.com/36078357/81524802-966a3200-9320-11ea-8829-01d18d15ec69.png)
Note: ignore the black line around it.

**Comment by glebka100500** [comment]
I did the other way around, for blue pixel the red values are on the diagonals and green are on the top, bottom and sides. The specification says that leftmost pixel is green and pixel to the right of it is blue, that means green must be on the side of blue pixel and red is below green so its across the diagonal from blue

**Comment by QiiLin** [comment]
Sorry... I wrote that question last night....and I wrote it wrong....for the blue pixel.. I used avg value of its horizontal, vertical as value for green. I also use the diagonal avg for the red.  For the red pixel, I still used the hor, ver for green and diagonal avg for blue.  For green pixel, there are two cases:
1. even row even col,  hor avg for blue, vertical avg for red.  2. odd row odd col, hor avg for red, vertical for blue.  the green color will remind the same. So in the green case, we only consider at maximum 4 pixels around. I wonder do we need to care about the diagonal pixel(which is green) ?

**Comment by QiiLin** [comment]
nvm... after taking a closer on my code ... somehow I take the avg wrong. But thanks for the response.

**Comment by glebka100500** [comment]
If I understood you follow up question correctly, yes I think we do need to compute averages for two different of green separately

**Comment by QiiLin** [comment]
so for the green pixel, the green color is the avg value of bayer value+ the vertical sum + the horizontal sum?

**Comment by glebka100500** [comment]
oh, you meant do we need to take the surrounding green color pixels into account when computing green color? No, we don't, since the value of each pixel in bayer is the "true" intensity of one of the colors of that pixel, so we don't need to add any other intensities to it

**Comment by QiiLin** [comment]
Got it thanks
