### ISSUE TITLE
desaturated image does not match exactly. 

### ISSUE THREAD

**Issue by QiiLin** [alecjacobson/computer-graphics-raster-images#53]
Hi guys, I have read the issue posted before, but the desaturated image I create does not match exactly with the image under the image folder.
my result: 
![image](https://user-images.githubusercontent.com/36078357/81575735-5d0fe180-9375-11ea-804e-a09ac991b347.png)
image from the folder:
![desaturated](https://user-images.githubusercontent.com/36078357/81575773-68fba380-9375-11ea-8799-73e44de19e38.png)

You can see that color around the eye does not really match...Is it tolerable ?

**Comment by MianWei8** [comment]
I would double check your code. It's not just the eyes, but the fur near the nose and in the ears also don't seem to be the right colour, there's a reddish tint to it in your version. Also I'm not sure why you included a border? So it's not clear to me that everything is correct, so I would verify this.

**Comment by QiiLin** [comment]
those borders are there because I did a screenshot.. so just ignore it for now...for the code. I check it let more than 3 times. it is the formula that was posted discussion. so I am really out of idea on what is wrong with the way I did here.  I did  s*(1-factor) as well.

**Comment by QiiLin** [comment]
I have some idea about why this is happening:
 when I did the conversion from rgb to hsv.. the r,g,b input is between 0 and 1...
so I did that /255.0 before I pass it into the rgb to hsv function.... and for the result from hsv_to_rgb, those r g b are being *255.0 and convert it back to from 0-255. I may lose some precision here during the divide and casting double to unsigned char...

**Comment by MianWei8** [comment]
Can you try  to just keep the RGB inputs between 0 and 1 and see what happens?

**Comment by QiiLin** [comment]
RGB input for rbg to hsv?

**Comment by MianWei8** [comment]
But you said "the r,g,b input is between 0 and 1" so why are you dividing by 255 again?

**Comment by QiiLin** [comment]
sorry about my wording
1. rgb for the desaturated  is unsigned char so 0 -255
2. rgb input for rgb_to_hsv need to be between 0 and 1.. so I did that / 255.0 in the desaturated  function before I pass those rgb value to the rgb_to_hsv.. this ensures that input of rgb_to_hsv is between 0 and 1.  I didn't do /255.0 inside the rgb_to_hsv function

**Comment by QiiLin** [comment]
Ok I tried to convert rgb to hsv and hsv to rgb back and forth ... the result is alignment with each other... so there should not be much issue with the conversion... feels bad.... still don't how to fix this...

**Comment by MianWei8** [comment]
Can you verify you get the correct HSV values with known colour values, there's a chart in the wikipedia page that tells you what you should get back under the heading "Examples".

**Comment by QiiLin** [comment]
I tried with yellow and green, it works ....

**Comment by kcovelli** [comment]
For what it's worth, I get the exact same output as @QiiLin, and to my eye it looks more correct than the example. Putting the example image in an image editor, it looks like the area in the ear and around the nose/eye is clipping for some reason (i.e saturation is 0) which shouldn't happen if we're supposed to be multiplying the saturation of each pixel by a (non-zero) factor unless I'm missing something. 

Applying a desaturation filter from the image editor gives an image that looks closer to our output than the example (though not exactly the same, I don't know exactly how this filter behaves so probably not a big deal)

my output: 
![image](https://user-images.githubusercontent.com/35745387/81611081-7716e780-93a8-11ea-9897-d6cfe78184a9.png)

image editor's output:
![image](https://user-images.githubusercontent.com/35745387/81611046-69616200-93a8-11ea-846b-eb20291ab6ef.png)

If an instructor could let us know if our output is alright that would be much appreciated!

**Comment by psarahdactyl** [comment]
My only guess as to what's causing these differences is the compression that PNGs the in the README have undergone. PPMs are an uncompressed format so comparing them exactly might not make sense. Maybe the raw values in your output PPMs are correct and the image compression changes the values in the PNGs. I would say the code you have now that generates these is probably right (especially if you tried those example values).
