### ISSUE TITLE
Confusion about simulating bayer pattern

### ISSUE THREAD

**Issue by jamil-asad** [alecjacobson/computer-graphics-raster-images#54]
So I understand the ordering "GBRG" for bayer pattern, even rows containing GBGB... and odd rows containing RGRG... 

But when creating the output which should be single channel, do we have to slide through each row in windows of 3 bytes (i.e 3 channels) and convert the first byte in each window to its respective grascale intensity and ignore the last 2 bytes in the window? For example the 2nd window at first row starts with a Blue channel so I multiply the value by "0.0722" and move on to the next window?

Following the above scheme, the output I get is a bit darker than what I see in the README.

**Comment by jamil-asad** [comment]
Also, are you guys able to obtain the exact same simulate bayer mosaic image as  shown in the README?

**Comment by MichaelWes** [comment]
I think you are overcomplicating simulating the Bayer pattern. Each pixel's RGB values map to a single intensity via a linear combination per the handout. (To maintain the PPM "P3" format, that intensity is just propagated three times in the output image, but that is an irrelevant detail). The GBRG pattern matters for performing "de-mosaicing".

I'm able to get the same thing as shown in the README as far as I can tell.

**Comment by jamil-asad** [comment]
In simple words, what I do is that for every pixel in the rgb vector, I take the channel value of the color that follows the bayer pattern and multiply it by its respective intensity in the grayscale conversion formula. 

My output image image looks similar in the sense that it has the interleaved pattern, but overall the image is a bit darker then the one in README.
