### ISSUE TITLE
Submission through GitHub

### ISSUE THREAD

**Issue by rikingurditta** [alecjacobson/computer-graphics-raster-images#55]
Hello!

In class, it was mentioned that we would submit assignments through GitHub, and Prof. Singh said that there are instructions on how to do this on the assignment handout (IIRC). However, the assignment instructions ask us to submit through MarkUs. How will submission really work?

Thanks!

**Comment by Marinette** [comment]
Near the end of the lecture, he mentioned that it would be submitted through MarkUs. The current link is not working and he told us to wait until Friday for it to be back up.

**Comment by rikingurditta** [comment]
@Marinette I didn't catch that, my bad. Thank you so much!
