### ISSUE TITLE
Unexpected values for width and height

### ISSUE THREAD

**Issue by Marinette** [alecjacobson/computer-graphics-raster-images#56]
I'm trying to write the header portions for my ppm file and I am getting unexpected values (big, negative values) saved in the width and height variables, resulting in the header looking like this:
```
P6
-858993460 -858993460
255
```
I was expecting the width and height to be 383 and 385. Not sure why I am getting these values. Did anyone encounter this?

**Comment by maxsours** [comment]
At a guess, I'd say you're grabbing values that haven't been initialized yet somehow, or maybe they're some weird type? How are you storing those values in the file? Also, you should be using P3 instead of P6 to make it easier for you to read.

**Comment by maxsours** [comment]
Also, if you are using Linux, you can enable debugging with gdb by running the command
cmake -DCMAKE_BUILD_TYPE=Debug ..
instead of 
cmake ..
which could probably help you figure out the issue

**Comment by Terlang** [comment]
check the image path in main.cpp. My output is build/Debug/raster.exe instead of build/raster.exe, so I changed path to **../../data/dog.png**

**Comment by Marinette** [comment]
Thanks guys. The issue was exactly what @Terlang mentioned. Windows users beware?
