### ISSUE TITLE
Average available neighbours for demosiac

### ISSUE THREAD

**Issue by DavidCollard** [alecjacobson/computer-graphics-raster-images#6]
Under "Mosaic images":
_"So for each pixel, we'll use the exact color sample when it's available and **average available neighbors (in all 8 directions)** to fill in missing colors."_

Does this mean that we should factor in the RGB values that we've already approximated? Wouldn't this lead to different results depending on what order we fill the pixels?

**Comment by psarahdactyl** [comment]
No, this means you should average the available neighbors from the original mosaic bayer.ppm to fill in the new image demosaicked.ppm.
