### ISSUE TITLE
Having problems on https://github.com/alecjacobson/computer-graphics-raster-images#execution

### ISSUE THREAD

**Issue by RioAraki** [alecjacobson/computer-graphics-raster-images#7]
When trying https://github.com/alecjacobson/computer-graphics-raster-images#execution

I found I am unable to run ./raster because `raster` is not found in the `build` directory. I didnt see any error during compile using `cmake ..` and here is the `ls` for `build` dir:
```
Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        2018/9/13      1:26                CMakeFiles
-a----        2018/9/13      1:26          44968 ALL_BUILD.vcxproj
-a----        2018/9/13      1:26            331 ALL_BUILD.vcxproj.filters
-a----        2018/9/13      1:26          13671 CMakeCache.txt
-a----        2018/9/13      1:26           1535 cmake_install.cmake
-a----        2018/9/13      1:26           3195 raster.sln
-a----        2018/9/13      1:26          58163 raster.vcxproj
-a----        2018/9/13      1:26           2797 raster.vcxproj.filters
-a----        2018/9/13      1:26          44146 ZERO_CHECK.vcxproj
-a----        2018/9/13      1:26            574 ZERO_CHECK.vcxproj.filters
```
I could see a raster.sln file. Ideally should an raster.exe comes out? What should I do to execute the raster output?

**Comment by DavidCollard** [comment]
cmake takes a list of system agnostic build instructions and generates an appropriate build file for that system. Here, that file is the .sln (you're probably using windows, or running cmake through an application which can build from a .sln). If you'd rather use a makefile, you can force it to build one of those.

Take a look at a tutorial like [this](http://preshing.com/20170511/how-to-build-a-cmake-based-project/) on using cmake.

**Comment by RioAraki** [comment]
got the idea after doing some research, thanks!
