### ISSUE TITLE
Issue with ppm file

### ISSUE THREAD

**Issue by wuyujie1** [alecjacobson/computer-graphics-raster-images#71]
I am using a windows device, the ppm file I generated all have negative size:

P3
-858993460 -858993460
255

I checked my write_ppm code and it looks normal, does anyone have any idea about this?

**Comment by KanverB** [comment]
Check https://github.com/alecjacobson/computer-graphics-raster-images/issues/56

**Comment by wuyujie1** [comment]
> Check #56

thanks!!
