### ISSUE TITLE
C features with CPP alternative

### ISSUE THREAD

**Issue by qe201020335** [alecjacobson/computer-graphics-raster-images#83]
I noticed that there are many C features that have a CPP alternative. Which one should I use? 

For example, open a file for write, the cpp way is to `std::ofstream out; out.open(filename);` 
but I can also do it the c way `FILE* outFile = fopen(filename.c_str(), "w");`

Are there any rules on this? May I use anyone I like?

**Comment by alecjacobson** [comment]
You can use either so long as it still compiles on the required setup.
