### ISSUE TITLE
Are we still submitting to MarkUs this year?

### ISSUE THREAD

**Issue by andyw1589** [alecjacobson/computer-graphics-raster-images#92]
In Karan's version of the assignment, it says we're supposed to submit to https://markus.teach.cs.toronto.edu/2022-01 , but I'm pretty sure that's for the previous winter semester? I also don't see CSC317 for this semester's MarkUs either, unless it hasn't been loaded yet?

**Comment by henrytwo** [comment]
I'm able to access it here: https://markus.teach.cs.toronto.edu/2022-09/courses

**Comment by andyw1589** [comment]
oh it just appeared for me too
